version: '3'
services:
  rabbitmq:
    image: devabhijeet/rabbitmq-extended
    # volumes:
    #   - ./rabbitmq/rabbit.conf:/etc/rabbitmq/rabbitmq.config
    # environment:
    #   - RABBITMQ_DEFAULT_USER=abhijeet
    #   - RABBITMQ_DEFAULT_PASS=asingh
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 3s
      timeout: 10s
      retries: 50
  taskmaster:
    image: devabhijeet/oj-taskmaster
    volumes:
      - '/tmp/runbox:/tmp/runbox'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  api:
    image: devabhijeet/oj-api
    depends_on:
      taskmaster:
        condition: service_started
    restart: on-failure
    ports:
      - '3008:3008'

    env_file:
      - .env

  worker-c:
    image: devabhijeet/oj-worker-c
  worker-cpp:
    image: devabhijeet/oj-worker-cpp
