const actionTypes = {
	ADD_ERROR: 'ADD_ERROR',
	REMOVE_ERROR: 'REMOVE_ERROR',
	SET_CURRENT_USER: 'SET_CURRENT_USER',

	SET_EDITOR_LANG: 'SET_EDITOR_LANG',
	SET_EDITOR_LANGS: 'SET_EDITOR_LANGS',
	SET_EDITOR_CODE: 'SET_EDITOR_CODE',
	SET_EDITOR_OUTPUT: 'SET_EDITOR_OUTPUT',
	SET_EDITOR_INPUT: 'SET_EDITOR_INPUT',
	SET_EDITOR_THEME: 'SET_EDITOR_THEME',
	RESET_EDITOR_CODE: 'RESET_EDITOR_CODE',
	SET_CODE_SUBMISSION_ID: 'SET_CODE_SUBMISSION_ID',
	SET_FILES: 'SET_FILES',
	ADD_FILE: 'ADD_FILE',
	EDIT_FILE: 'EDIT_FILE',
	DELETE_FILE: 'DELETE_FILE',
	SET_FOLDERS: 'SET_FOLDERS',
	SET_UPLOAD_STATUS: 'SET_UPLOAD_STATUS',
	ADD_UPLOAD: 'ADD_UPLOAD',
	EDIT_UPLOAD: 'EDIT_UPLOAD',
	RESET_UPLOADS: 'RESET_UPLOADS',
	CANCE_UPLOAD: 'CANCEL_UPLOAD',
}

export default actionTypes
