const actionTypes = {
  ADD_ERROR: 'ADD_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
  SET_CURRENT_USER: 'SET_CURRENT_USER',

  SET_EDITOR_LANG: 'SET_EDITOR_LANG',
  SET_EDITOR_LANGS: 'SET_EDITOR_LANGS',
  SET_EDITOR_CODE: 'SET_EDITOR_CODE',
  SET_EDITOR_OUTPUT: 'SET_EDITOR_OUTPUT',
  SET_EDITOR_INPUT: 'SET_EDITOR_INPUT',
  SET_EDITOR_THEME: 'SET_EDITOR_THEME',
  RESET_EDITOR_CODE: 'RESET_EDITOR_CODE',
  SET_CODE_SUBMISSION_ID: 'SET_CODE_SUBMISSION_ID',
};

export default actionTypes;
